### ISSUE TITLE
Question about Quality-aware weights

### ISSUE THREAD

**Issue by LZL-CS** [CVMI-Lab/HybridNeuralRendering#1]
Hi, thanks for sharing your awesome work. When I tried to run your code Quality-aware weights, I found that the packages missed as follows: 
<img width="902" alt="image" src="https://github.com/CVMI-Lab/HybridNeuralRendering/assets/54640259/4f7ea081-ffc5-4b1f-be84-b01de5990aa7">

And you mention that **The weights have been included in the "frame_weights_step5" folder**, but I also don't find it. I appreciate any help you can provide!

**Comment by daipengwa** [comment]
First, the code uses "sys.path.append('core')" to include functions in the folder "core", you can directly run it. Alternatively, you can directly import specific functions in the "./core". 

Second, the pre-computed frame weights are in "data_src/scannet/frame_weights_step5/xxx.npy"

**Comment by LZL-CS** [comment]
Got it and thanks for your reply!
